pub mod auth;
mod common;
pub mod config;
pub mod course;
pub mod exam_num;
pub mod feedback;
pub mod flex_time;
pub mod message;
pub mod notice;
pub mod ping;
pub mod record;
pub mod survey;
pub mod user;
pub mod user_settings;
pub mod zhihu;
