stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - cd /root/project/rust-back-2024/src/back_2024
    - git pull
    - cargo build --release
    - cd /root/project/rust-back-2024/
    - systemctl stop back
    - sleep 1
    - cp ./src/back_2024/target/release/back_2024 ./
    - systemctl start back
    - cd /root/project/rust-back-2024/src/back_2024
    - cargo clean
  only:
    - master