[package]
name = "back_2024"
version = "1.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# 引入这个依赖是为了在 musl 上成功编译 openssl（引入了 lapin 导致需要这样的）
[target.'cfg(not(windows))'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[dependencies]
salvo = { version = "0.80.0", features = ['cors', "logging"] }
chrono = { version = "0.4.37", features = ["serde"] }
anyhow = "1.0.81"
# analytics = { version = "0.1.0", path = "./lib/analytics" }
# cache_map = {version = "0.1.0", path = "./lib/cache_map"}
clia-tracing-config = "0.2.7"
flurry = "0.5.1"
jsonwebtoken = "9.3.0"
lapin = "3.7.0"
rand = "0.8.5"
regex = { version = "1.11.1", default-features = false, features = [
    "unicode-perl",
] }
reqwest = { version = "0.12.2", default-features = false, features = [
    #"default-tls",
    "rustls-tls",
] }
serde = "1.0.197"
serde_json = { version = "1.0.115" }
# serde_json = { version = "1.0.111", features = ["preserve_order"] }
# serde_yaml = "0.9.34"
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio", "chrono"] }
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = [
    "rt-multi-thread",
    "macros",
    "signal",
] }
toml = "0.8.12"
tracing = "0.1.40"
aes = "0.8.4"
cbc = { version = "0.1.2", features = ["alloc", "std"] }
base64 = "0.22.1"
rand_core = { version = "0.6.4", features = ["std"] }
md5 = "0.8.0"
dashmap = "6.1.0"
prometheus = "0.14"
uuid = { version = "1.22.0", features = ["v4"] }
futures = "0.3.32"
moka = { version = "0.12.15", features = ["future"] }
sha2 = "0.11.0"
hex = "0.4.3"
rsa = { version = "0.9.10", features = ["pem", "sha2"] }
hnu_query = { version = "0.3.0" }

#[dev-dependencies]

#[profile.release] # 优化发布release编译时的性能和体积，但会影响编译时间，完整编译大约两分钟多
#opt-level = 3
#debug = false
#codegen-units = 1       # 代码单元联合优化
#lto = "fat"             # 链接时优化，降低编译速度
#overflow-checks = false # 溢出检查
