[package]
name = "back_2024"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.rust]
unsafe_code = "forbid"
# unused = "allow"       # for exploratory development

[dependencies]
anyhow = "1.0.81"
axum = { version = "0.7.5", features = ["macros"] }
# analytics = { version = "0.1.0", path = "./lib/analytics" }
# cache_map = {version = "0.1.0", path = "./lib/cache_map"}
chrono = { version = "0.4.37", features = ["serde"] }
clia-tracing-config = "0.2.7"
flurry = "0.5.1"
jsonwebtoken = "9.3.0"
lazy_static = "1.4.0"
once_cell = "1.19.0"
rand = "0.8.5"
redis = { version = "0.25.2", default-features = false, features = [
    "tokio-comp",
] }
regex = { version = "1.11.1", default-features = false }
reqwest = { version = "0.12.2", default-features = false, features = [
    "default-tls",
    # "rustls-tls",
] }
serde = "1.0.197"
serde_json = { version = "1.0.115" }
# serde_json = { version = "1.0.111", features = ["preserve_order"] }
# serde_yaml = "0.9.34"
sqlx = { version = "0.7.4", features = ["mysql", "runtime-tokio", "chrono"] }
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = [
    "rt-multi-thread",
    "macros",
    "signal",
] }
toml = "0.8.12"
tower-http = { version = "0.5.2", features = [
    "validate-request",
    "trace",
    "timeout",
    "cors",
] }
tracing = "0.1.40"

#[dev-dependencies]

#[profile.release] # 优化发布release编译时的性能和体积，但会影响编译时间，完整编译大约两分钟多
#opt-level = 3
#debug = false
#codegen-units = 1       # 代码单元联合优化
#lto = "fat"             # 链接时优化，降低编译速度
#overflow-checks = false # 溢出检查
