on:
  release:
    types: [published]

jobs:
  upload-assets:
    env:
      RUNNER_TOOL_CACHE: /toolcache
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/rust-kotlin/setup-rust@v1
        with:
          targets: 'x86_64-unknown-linux-musl'
          cache-target: ''  # 留空表示整个target目录
      - name: Build
        run: |
          cargo build --release --bin back_2024 --target x86_64-unknown-linux-musl
      - uses: https://github.com/akkuman/gitea-release-action@v1
        with:
          files: |-
            target/x86_64-unknown-linux-musl/release/back_2024