on:
  release:
    types: [published]

jobs:
  upload-assets:
    env:
      RUNNER_TOOL_CACHE: /toolcache
    runs-on: ubuntu-22.04
    steps:
      - uses: https://gitee.com/skr2005/checkout@v5

      - name: Setup Toolchain
        uses: ./.gitea/workflows/setup-toolchain

      - name: Build All Binaries
        run: |
          cargo build --release --bins --target x86_64-unknown-linux-musl

      - uses: https://gitee.com/skr2005/gitea-release-action@v1
        with:
          files: |-
            target/x86_64-unknown-linux-musl/release/back_2024
            target/x86_64-unknown-linux-musl/release/spider_2024

      - name: Setup SSH for Uploading back_2024
        uses: https://gitee.com/greyCloud/ssh-key-action.git@v2
        with:
          key: ${{ secrets.SSH_KEY_118 }}
          known_hosts: unnecessary

      - name: Deploy back_2024 to Server
        run: |
          apt-get install -y sshpass
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME_118 }}@${{ secrets.SSH_SERVER_118 }} << 'EOF'
          systemctl stop back
          EOF
          sshpass scp -o StrictHostKeyChecking=no \
            -P 22 target/x86_64-unknown-linux-musl/release/back_2024 \
            ${{ secrets.SSH_USERNAME_118 }}@${{ secrets.SSH_SERVER_118 }}:${{ vars.BACK_DEPLOY_DIR }}/
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME_118 }}@${{ secrets.SSH_SERVER_118 }} << 'EOF'
          chmod +x ${{ vars.BACK_DEPLOY_DIR }}/back_2024
          systemctl restart back
          EOF
