name: Setup Toolchain

runs:
  using: 'composite'
  steps:
    - name: Rustup Mirror
      run: |
        echo "RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup" >> $GITHUB_ENV
        echo "RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup" >> $GITHUB_ENV

    - name: Setup Toolchain
      uses: https://gitee.com/skr2005/setup-rust-toolchain@main
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        components: clippy, rustfmt
        cache-all-crates: "true"
        
    - run: echo "/root/.cargo/bin" >> $GITHUB_PATH

    - name: Crates Mirror
      run: |
        mkdir -vp ${CARGO_HOME:-$HOME/.cargo}

        cat << EOF | tee -a ${CARGO_HOME:-$HOME/.cargo}/config.toml
        [source.crates-io]
        replace-with = 'ustc'

        [source.ustc]
        registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

        [registries.ustc]
        index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
        EOF