name: PR Check

on:
  push: # 允许main分支更新时再检查一遍，这是为了使得action对缓存更友好，见 https://docs.github.com/zh/actions/reference/dependency-caching-reference#restrictions-for-accessing-a-cache
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          components: clippy, rustfmt
          cache-all-crates: "true"

      - name: Setup .env
        env:
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: echo "DATABASE_URL=$TEST_DATABASE_URL" > .env

      - name: Clippy
        run: cargo clippy --bins --tests --examples -- -D warnings

      - name: Test Documentation Items
        run: cargo doc --document-private-items --no-deps

      - name: Check Code Format
        run: cargo fmt --check
